### ISSUE TITLE
term and url encoding

### ISSUE THREAD

**Issue by MartyIX** [naitian/dictcc-js#1]
Hi,

I believe the line https://github.com/naitian/dictcc-js/blob/master/index.js#L67:

```
url: 'http://' + from + to + '.dict.cc/?s=' + term,
```

should be

```
url: 'http://' + from + to + '.dict.cc/?s=' + encodeURIComponent(term),
```

Best regards,
Martin

**Comment by naitian** [comment]
Yes, I think you are correct, thanks for bringing this to my attention!

**Comment by naitian** [comment]
This has been fixed.
